---
- name: Set Up Fresh Ubuntu
  hosts: all
  become: yes

  pre_tasks:
    - name: Check if the setup has already been completed (using shell)
      shell: |
        if [ -f /etc/system_prep_complete ]; then echo "exists"; else echo "missing"; fi
      register: prep_marker
      changed_when: false

    - name: Debug marker file check result
      debug:
        msg: "Prep marker file is {{ prep_marker.stdout }}"

    - name: Skip host if setup is already completed
      meta: end_play
      when: prep_marker.stdout == "exists"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all packages
      apt:
        upgrade: dist
        autoremove: yes

    - name: Install common utilities
      apt:
        name:
          - fail2ban
          - nano
          - cron
          - clamav
          - clamav-daemon
          - clamav-freshclam
          - curl
        state: present

    - name: Ensure cron service is running
      service:
        name: cron
        state: started
        enabled: yes

    - name: Ensure ClamAV log directory exists
      file:
        path: /var/log/clamav
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Add weekly apt update/upgrade cron job
      cron:
        name: "Weekly system update"
        user: root
        minute: "0"
        hour: "1"
        weekday: "0"
        job: "apt update && apt upgrade -y && sudo apt autoremove >> /var/log/weekly-updates.log 2>&1"

    - name: Schedule weekly ClamAV scan
      cron:
        name: "Weekly ClamAV scan"
        user: root
        minute: "0"
        hour: "5"
        weekday: "0"
        job: "clamscan -r / --quiet --log=/var/log/clamav/weekly_scan.log"

    - name: Schedule weekly ClamAV definition update
      cron:
        name: "Weekly ClamAV definition update"
        minute: "0"
        hour: "3"
        weekday: "0"
        job: "systemctl stop clamav-freshclam && freshclam && systemctl start clamav-freshclam && systemctl enable clamd@scan && systemctl start clamd@scan"

    - name: Create marker file to indicate setup is complete
      file:
        path: /etc/system_prep_complete
        state: touch

    - name: Echo success message
      debug:
        msg: "System prepared and cron job scheduled successfully!"
