---
- name: Gravity Update for PiHole
  hosts: pihole_vms
  become: yes

  tasks:
    - name: Gravity Update cron
      cron:
        name: "Gravity Update for PiHole"
        user: root
        minute: "0"
        hour: "0"
        job: "/usr/local/bin/pihole updateGravity > /dev/null"
